In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data Understanding

Objective:
Understand dataset structure, time range, variables and data quality.

In [4]:
df=pd.read_csv("../data/raw/bitcoin_dataset.csv")

In [5]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,457.334015,21056800
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,424.440002,34483200
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,394.795990,37919700
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,408.903992,36863600
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,398.821014,26580100

In [6]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4280 entries, 0 to 4279
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4280 non-null   object
 1   Open       4280 non-null   float64
 2   High       4280 non-null   float64
 3   Low        4280 non-null   float64
 4   Close      4280 non-null   float64
 5   Adj Close  4280 non-null   float64
 6   Volume     4280 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 234.2+ KB

,Open,High,Low,Close,Adj Close,Volume
count,4280.000000,4280.000000,4280.000000,4280.000000,4280.000000,4.280000e+03
mean,28623.330630,29188.324150,28019.749124,28636.451670,28636.451670,2.230348e+10
std,32442.204251,32986.012544,31852.792883,32442.454923,32442.454923,2.294359e+10
min,176.897003,211.731003,171.509995,178.102997,178.102997,5.914570e+06
25%,3452.187439,3504.092224,3391.943420,3458.813721,3458.813721,1.676575e+09
50%,11536.727539,11850.328613,11288.414062,11564.331543,11564.331543,1.802679e+10
75%,46401.472656,47432.591797,45184.174805,46446.924805,46446.924805,3.446429e+10
max,124752.140625,126198.070312,123196.046875,124752.531250,124752.531250,3.509679e+11

In [7]:
df["Date"]=pd.to_datetime(df["Date"])

In [8]:
print(df["Date"].min())
print(df["Date"].max())

2014-09-17 00:00:00
2026-06-05 00:00:00